name: face_attendance
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animations: ^2.0.1
  cached_network_image: ^3.1.0
  flutter:
    sdk: flutter

  get: ^4.3.8
  google_fonts: ^2.1.0
  intl: ^0.17.0
  lottie: ^1.1.0
  shimmer: ^2.0.0
  image_picker: ^0.8.4
  image_cropper: ^1.4.1
  syncfusion_flutter_calendar: ^19.2.60
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  url_launcher: ^6.0.10

  firebase_core: ^1.10.0
  firebase_auth: ^3.2.0
  cloud_firestore: ^3.1.0
  firebase_messaging: ^11.1.0
  firebase_storage: ^10.1.0
  retry: ^3.1.0
  path_provider: ^2.0.5
  http: ^0.13.3
  flutter_cache_manager: ^3.1.2
  fluttertoast: ^8.0.8
  google_maps_flutter: ^2.0.11
  get_storage: ^2.0.3
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.6.1
  connectivity_plus: ^2.0.2
  data_connection_checker_tv: ^0.3.5-nullsafety
  encrypt: ^5.0.1
  visibility_detector: ^0.2.0
  dartz: ^0.10.0
  worker_manager: ^4.2.5
  flutter_email_sender: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  plugin:
    platforms:
      android:
        package: com.ttv.attendance
        pluginClass: CamerakitPlugin
      ios:
        pluginClass: CamerakitPlugin

  assets:
    - assets/images/intro/
    - assets/images/logos/
    - assets/images/illustration/
    - assets/lottie/
    - assets/mapstyle/
